sync:
  defaults:
    mode: two-way-resolved
    symlink:
      mode: "posix-raw"
    permissions:
      defaultFileMode: "0644"
      defaultDirectoryMode: "0755"
    ignore:
      vcs: true
      paths:
        # System files
        - ".DS_Store"
        - "._*"

        # IDE, misc files
        - ".idea"
        - ".magento"
        - ".docker"
        - "*.gz"
        - "*.zip"
        - "*.bz2"
        - ".github"
