<?php
/** @var Magento\Framework\View\Element\Template $block */
?>
<div class="devAll-post-list">
    <p><strong><?= __('DevAll posts') ?></strong></p>
    <ol>
        <li><a href="<?= $block->getUrl('devall/alliance/GroupTemplate', ['id' => 1]) ?>">Post 1</a></li>
        <li><a href="<?= $block->getUrl('devall/alliance/GroupTemplate', ['id' => 2]) ?>">Post 2</a></li>
        <li><a href="<?= $block->getUrl('devall/alliance/GroupTemplate', ['id' => 3]) ?>">Post 3</a></li>
    </ol>
</div>
